[tool.isort]
line_length = 120
profile = 'black'
py_version=38
skip_glob = [
  ".venv/**",
  "br-*/**",
  "branch-*/**",
  "libs/**",
  "resources/**",
  "stubs/**",
  "typings/**",
  "vendor/**",
  "venv/**",
]

[tool.black]
line-length = 120
target-version = ['py38']

# regex
exclude = '''
/(
  \.git |
  language-server |
  plugin/libs |
  resources |
  stubs
)/
'''
