[tool.black]
preview = true # use latest feature
line-length = 120
target-version = ['py38']
exclude = '''
/(
  \.git |
  \.venv(-.*)? |
  language-server |
  plugin/libs |
  resources |
  stubs |
  typings |
  _resources
)/
'''

[tool.pyright]
pythonVersion = '3.11'

[tool.ruff]
preview = true
select = ["E", "F", "W", "I"]
ignore = [
  "E203",
  "F401", # we still need to use type annotation in comments in py33
]
line-length = 120
target-version = 'py38'
exclude = [
  ".git",
  ".mypy_cache",
  ".venv",
  ".venv-*",
  "branch-*",
  "libs",
  "plugin/libs",
  "stubs",
  "tests/files",
  "typings",
  "vendor",
  "venv",
  "venv-*",
]
